### ISSUE TITLE
No syntax highlighting

### ISSUE THREAD

**Issue by adampielach** [enkia/enki-theme#13]
I've tried to set everything as you have described, but I cannot make highlighting for syntax work. For example, "this" keyword or "class" are not italics and different fonr as on your screenshots. How to make it work with your theme? I am also using the font that you use, but still no luck.
![sublime](https://user-images.githubusercontent.com/23332779/29270023-ed512ed4-80f4-11e7-8d0a-f41dab0997b8.jpg)

My settings: 

`{
	"always_show_minimap_viewport": true,
	"auto_complete_commit_on_tab": true,
	"auto_complete_with_fields": true,
	"bold_folder_labels": false,
	"caret_style": "wide",
	"color_scheme": "Packages/User/Color Highlighter/themes/Enki.tmTheme",
	"copy_with_empty_selection": false,
	"create_window_at_startup": false,
	"detect_indentation": true,
	"enki_theme_accent_red": true,
	"enki_theme_compact_sidebar": true,
	"enki_theme_panel_separator": true,
	"enki_theme_small_statusbar": true,
	"enki_theme_small_tab": true,
	"enki_theme_tabs_autowidth": true,
	"enki_theme_tree_headings": false,
	"folder_exclude_patterns":
	[
		".bundle",
		".git",
		".hg",
		".sass-cache",
		".svn",
		"bin",
		"CVS",
		"tmp"
	],
	"font_face": "InputMono",
	"font_options":
	[
		"gray_antialias",
		"subpixel_antialias"
	],
	"font_size": 12,
	"ignored_packages":
	[
		"CSS",
		"Vintage"
	],
	"indent_guide_options":
	[
		"draw_normal",
		"draw_active"
	],
	"line_padding_bottom": 2,
	"line_padding_top": 2,
	"overlay_scroll_bars": "enabled",
	"theme": "Enki-Theme.sublime-theme"
}
`

**Comment by enkia** [comment]
My README states Input but actually that's outdated. I'm using Operator Mono now (screenshots reflect that) which heavily emphasize italics. Input's italics are very subtle comparatively. Apologies for leading you down that path!

Secondly, I italicize very little. Keywords this, new, import, include, and comments come to mind. HTML markup isn't italicized except for the comments.  

Do you see any italics when using a font such as Operator Mono or [Fira Mono](https://github.com/tonsky/FiraCode)? Also, when I use Input font, the setting is "Input", not "InputMono" or "Fira Mono" rather than "FiraMono."
